events {}

http {
  server {
    listen 80;
    server_name devpro.biz www.devpro.biz;

    # Certbot challenge ke liye
    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    # Baaki sab HTTPS pe bhejo
    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 443 ssl;
    server_name devpro.biz www.devpro.biz;

    ssl_certificate /etc/letsencrypt/live/devpro.biz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/devpro.biz/privkey.pem;

    location / {
      proxy_pass http://frontend:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api {
      proxy_pass http://backend:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}